using UnityEngine;
using UnityEngine.EventSystems;
using TMPro;
using UnityEngine.UI;
using System.Collections;

[RequireComponent(typeof(TMP_Dropdown))]
public class TMPDropdownAutoScroll : MonoBehaviour, IPointerClickHandler
{
    private TMP_Dropdown _dropdown;

    void Awake()
    {
        _dropdown = GetComponent<TMP_Dropdown>();
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        // When clicked, start a coroutine to wait for the dropdown list to be created
        StartCoroutine(ScrollToSelected());
    }

    private IEnumerator ScrollToSelected()
    {
        // Wait for the end of the frame so the "Dropdown List" object is instantiated
        yield return new WaitForEndOfFrame();

        // Find the "Dropdown List" generated by TMP
        GameObject list = GameObject.Find("Dropdown List");
        if (list == null) yield break;

        ScrollRect scrollRect = list.GetComponentInChildren<ScrollRect>();
        if (scrollRect == null) yield break;

        // Calculate the normalized position (0 is bottom, 1 is top)
        // We invert the value because dropdowns are ordered top-to-bottom
        float itemCount = _dropdown.options.Count;
        float selectedIndex = _dropdown.value;

        if (itemCount > 1)
        {
            float targetPos = 1f - (selectedIndex / (itemCount - 1f));
            scrollRect.verticalNormalizedPosition = Mathf.Clamp01(targetPos);
        }
    }
}